<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Mine.Wpf.Controls\Mine.Wpf.Controls.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Mine.Wpf.Controls.Gallery</AssemblyName>
    <RootNamespace>Mine.Wpf.Controls.Gallery</RootNamespace>
  </PropertyGroup>

</Project>

